### ISSUE TITLE
Congestion control over SMS

### ISSUE THREAD

**Issue by ektrah** [t2trg/transports#11]
Do retransmissions with exponential back-off make sense for SMS?

**Comment by bsilverajan** [comment]
Giving this a little thought, I'd go with saying yes, as long as the MAX_RETRANSMIT value is kept low (which the current default of 4 seems to be). 

However it could potentially open a use case for abuse of SMS transmissions to unsuspecting receivers or battery drain attacks (the latter also affecting non-SMS CoAP nodes), if the MAX_RETRANSMIT parameter is set to a high value.

**Comment by bsilverajan** [comment]
Crossreferencing this to #14

**Comment by bsilverajan** [comment]
Update: 

The LWM2M spec has this to say about SMS binding: "CoAP retransmission is disabled for this binding."
