### ISSUE TITLE
Clarify the main use case of CoAP over SMS

### ISSUE THREAD

**Issue by ektrah** [t2trg/transports#14]
Is wake-up-of-LWM2M-sleepy-devices still the main use case, or have other use cases appeared?

**Comment by bsilverajan** [comment]
Cross referencing also to #15

**Comment by jaimejim** [comment]
AFAIK the use of sms is to wake up the device mostly. One reason is that not every country has flatrates for sms and it could get expensive, another is that the bandwidth provided by sms is not huge.

In some cases when the regular (wifi, wired, other) connection breaks, sms can be used as fallback.
It also varies depending on whether the radio is GSM, 3G or NB-IoT, but I am not familiar with the radio properties.Paging will also vary and thus the battery consumption.

**Comment by bsilverajan** [comment]
As an action point, the decision is to produce an applicability document outlining CoAP usage/interest over non-IP transports.
