### ISSUE TITLE
Find implementations of CoAP over SMS

### ISSUE THREAD

**Issue by ektrah** [t2trg/transports#15]
Are there implementations of draft-becker-core-coap-sms-gprs, LWM2M-over-SMS, or any ad-hoc solutions?

**Comment by bsilverajan** [comment]
Email discussion with OMA people earlier this year revealed that an SMS implementation exists from AvSystems which implements part of the LwM2M specification which also includes DTLS protection.

**Comment by inesrob** [comment]
Mechanism
https://github.com/AVSystem/Anjay

Support for UDP Binding
Support for SMS Binding (commercial version only)

**Comment by inesrob** [comment]
Commercial option: https://ioterop.com/iowa/
