### ISSUE TITLE
OMA usage of CoAP over SMS URI

### ISSUE THREAD

**Issue by bsilverajan** [t2trg/transports#17]
Based on today's discussion with the OMA folks, the issue tracks how (and if) the OMA is using a URI to describe resources reachable for CoAP over SMS. 

Involving @akeranen and @hannestschofenig into this issue.

Related issues: #4

**Comment by inesrob** [comment]
Page 37,38 of [1]

Registration Interface:
Operation: Register, CoAP method: POST, URI: /rd?ep={Endpoint Client Name}&lt={Lifetime}&lwm2m={version}&b={binding}&Q&sms={MSISDN}

Operation: Update, CoAP method: POST, URI: /{location}?lt={Lifetime}&b={binding}&Q&sms={MSISDN}

Example (Page 49 of [1]): Device Registration with UDP binding, Queue Mode and SMS Trigger:
POST /rd?ep=node&lwm2m=1.1&lt=86400&b=U&Q&sms=12345678</1/2>, </3/0>

 [1] OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A

**Comment by chrysn** [comment]
That seems to be the most URI-ish thing they use in OMA, and as it doesn't really fit URI for the coap+sms:// URI question, it's safe to assume that they don't use any URIs for resources on CoAP-over-SMS.
