### ISSUE TITLE
Align draft with CoAP over SMS in LwM2M

### ISSUE THREAD

**Issue by ektrah** [t2trg/transports#4]

**Comment by inesrob** [comment]
Lightweight Machine to Machine Technical Specification:
Transport Bindings (2019-06-17): http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A.pdf describes SMS with LwM2M (SMS Channel Security, SMS Binding, etc.)

**Comment by ektrah** [comment]
@jaimejim provided some insights on the current state of the SMS binding in LwM2M a while ago, but I can't find my notes.

**Comment by jaimejim** [comment]
AFAIK OMA DM uses a version of coap+sms and has an implementation.
They did test it at some point few year ago in one of the regular interop events.
I htink the input from OMA would be valuable, specially as to how they implement sms transport. 
It might well be that they simply encapsulate the payload over sms without much "coap" on it.

**Comment by inesrob** [comment]
Implementation of AVSystem 
https://github.com/AVSystem/Anjay

Mechanism:
Support for UDP Binding
Support for SMS Binding (commercial version only)

**Comment by inesrob** [comment]
OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A
http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A.pdf
