### ISSUE TITLE
Review draft-becker-core-coap-sms-gprs-06

### ISSUE THREAD

**Issue by ektrah** [t2trg/transports#9]

**Comment by bsilverajan** [comment]
Previous input from OMA: 

"draft-becker-core-coap-sms-gprs-06 does not describe the transport of DTLS-protected CoAP packets, which the LwM2M specification does."

The LWM2M Transport spec explain the transport for CoAP messages and it also contains a section about the SMS transport. It is available at [https://www.openmobilealliance.org/release/LightweightM2M/V1_1-20180710-A/OMA-TS-LightweightM2M_Transport-V1_1-20180710-A.pdf](https://www.openmobilealliance.org/release/LightweightM2M/V1_1-20180710-A/OMA-TS-LightweightM2M_Transport-V1_1-20180710-A.pdf)
